### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by lARSHADl** [AndeYashwanth/JNTUHResults#1]
Can you Explain how the code works in detail and how did you parse the result since it contains multiple table.
and why did you used request specifically instead of selenium ?

**Comment by AndeYashwanth** [comment]
I created this repo when I was not that good at writing programs. Code basically does is send request to jntu result server using requests module for each rollno and extract the response of each subject from the response html page and store it in mysql table. I used beautiful soup module to extract data from tables. 

If you use selenium then you only will be able to see each result in each browser tab, but when you use requests you can store all the results in one db table and view easily.

Updated code and readme to make it easier to understand and run.
I didn't verify display_results.php as I currently don't have xampp installed.

**Comment by lARSHADl** [comment]
Thanks , Your Awsome !
